//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculadora_Indice_Academico
{
    using System;
    using System.Collections.Generic;
    
    public partial class administrador
    {
        public int administrador_id { get; set; }
        public string administrador_cedula { get; set; }
        public string administrador_nombres { get; set; }
        public string administrador_apellidoP { get; set; }
        public string administrador_apellidoM { get; set; }
        public string administrador_telefono { get; set; }
        public string administrador_correo { get; set; }
        public string administrador_contrasena { get; set; }
    }
}
