//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculadora_Indice_Academico
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Aseguramiento_bdEntities : DbContext
    {
        public Aseguramiento_bdEntities()
            : base("name=Aseguramiento_bdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<administrador> administradors { get; set; }
        public virtual DbSet<area> areas { get; set; }
        public virtual DbSet<aula> aulas { get; set; }
        public virtual DbSet<calificacion> calificacions { get; set; }
        public virtual DbSet<carrera> carreras { get; set; }
        public virtual DbSet<docente> docentes { get; set; }
        public virtual DbSet<estudiante> estudiantes { get; set; }
        public virtual DbSet<estudianteHistorico> estudianteHistoricoes { get; set; }
        public virtual DbSet<materia> materias { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tipo_aula> tipo_aula { get; set; }
        public virtual DbSet<trimestre> trimestres { get; set; }
        public virtual DbSet<trimestre_materia> trimestre_materia { get; set; }
    }
}
