//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculadora_Indice_Academico
{
    using System;
    using System.Collections.Generic;
    
    public partial class calificacion
    {
        public int estudiante_id { get; set; }
        public int triMat_id { get; set; }
        public Nullable<decimal> medioTermino { get; set; }
        public Nullable<decimal> calificacionFinal { get; set; }
        public Nullable<decimal> eval1 { get; set; }
        public Nullable<decimal> eval2 { get; set; }
        public Nullable<decimal> eval3 { get; set; }
        public Nullable<decimal> eval4 { get; set; }
        public string comentario { get; set; }
    
        public virtual estudiante estudiante { get; set; }
        public virtual trimestre_materia trimestre_materia { get; set; }
    }
}
