//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculadora_Indice_Academico
{
    using System;
    using System.Collections.Generic;
    
    public partial class docente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public docente()
        {
            this.area = new HashSet<area>();
            this.carrera = new HashSet<carrera>();
            this.trimestre_materia = new HashSet<trimestre_materia>();
        }
    
        public int docente_id { get; set; }
        public string docente_cedula { get; set; }
        public string docente_nombres { get; set; }
        public string docente_apellidoP { get; set; }
        public string docente_apellidoM { get; set; }
        public string docente_telefono { get; set; }
        public string docente_correo { get; set; }
        public int area_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<area> area { get; set; }
        public virtual area area1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carrera> carrera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trimestre_materia> trimestre_materia { get; set; }
    }
}
