//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculadora_Indice_Academico
{
    using System;
    using System.Collections.Generic;
    
    public partial class materia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public materia()
        {
            this.trimestre_materia = new HashSet<trimestre_materia>();
        }
    
        public int materia_id { get; set; }
        public string materia_nombre { get; set; }
        public string materia_codigo { get; set; }
        public int carrera_id { get; set; }
        public int materia_creditos { get; set; }
        public int tipo_aula_id { get; set; }
    
        public virtual carrera carrera { get; set; }
        public virtual tipo_aula tipo_aula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trimestre_materia> trimestre_materia { get; set; }
    }
}
